### ISSUE TITLE
Backend cannot be deployed with No prebuild or local build of @parcel/watcher found error.

### ISSUE THREAD

**Issue by rnrnstar2** [aws-amplify/amplify-backend#1360]
### Environment information

```plain text
npx amplify info                                                                                                          【 main 】
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M2 Pro
  Memory: 220.56 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.5.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 9.8.0 - /usr/local/bin/npm
  pnpm: 8.15.5 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/backend: 0.13.0-beta.20
  @aws-amplify/backend-cli: 0.12.0-beta.22
  aws-amplify: 6.0.28
  aws-cdk: 2.138.0
  aws-cdk-lib: 2.138.0
  typescript: 5.4.5
AWS environment variables:
  AWS_PROFILE = cloudteam
  AWS_DEFAULT_PROFILE = cloudteam
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

```
version: 1
applications:
  - appRoot: packages/shared-backend
    backend:
      phases:
        build:
          commands:
            - echo *** BACKEND BUILD ***
            - npm install
            - npx amplify pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
            - ls -al
    frontend:
      phases:
        build:
          commands:
            - echo *** FRONTEND BUILD ***
            - node -v
            - amplify -v
      artifacts:
        baseDirectory: /
        files:
          - "**/*"
      cache:
        paths: []

```

```
[WARNING]: /codebuild/output/src2094350622/src/Oripa/node_modules/@parcel/watcher/index.js:26

throw new Error(`No prebuild or local build of @parcel/watcher found. Tried ${name}. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.`);

Error: No prebuild or local build of @parcel/watcher found. Tried @parcel/watcher-linux-x64-glibc. Please ensure it is installed (don't use --no-optional when installing with npm). Otherwise it is possible we don't support your platform yet. If this is the case, please report an issue to https://github.com/parcel-bundler/watcher.

at Object.<anonymous> (/codebuild/output/src2094350622/src/Oripa/node_modules/@parcel/watcher/index.js:26:13)

at Module._compile (node:internal/modules/cjs/loader:1256:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
at Module.load (node:internal/modules/cjs/loader:1119:32)
at Module._load (node:internal/modules/cjs/loader:960:12)
at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

"@aws-amplify/backend": "^0.13.0-beta.15",
     "@aws-amplify/backend-cli": "^0.12.0-beta.17",

I get an error when trying to generate a backend with the latest version.
The sandbox was created using this version, so if you downgrade due to code differences, another error will occur, so please fix the bug.
