### ISSUE TITLE
Build Error NextJS(14.2.3) - "your app's framework looks wrong."

### ISSUE THREAD

**Issue by thedevopsguyblog** [aws-amplify/amplify-backend#1562]
### Environment information

```plain text
> npx ampx info
npm ERR! could not determine executable to run
```

### Description

When amplify executes the build phase `npm run build` it produces the following...
`2024-05-26T20:30:45.849Z [ERROR]: !!! CustomerError: It looks like you are attempting to deploy a Next.js SSR app, but your app's framework looks wrong. Please update your app's framework to 'Next.js - SSR' to ensure that your app is deployed correctly.`

my buildspec.yml looks like this...
```yml
version: 1
applications:
- appRoot: frontend
  frontend:
    buildPath: /frontend
    phases:
      preBuild:
        commands:
          - npm ci
      build:
        commands:
          - npm run build
    artifacts:
      baseDirectory: .next
      files:
        - '**/*'
    cache:
      paths:
        - node_modules/**/*
```

the cdk construct deploying my app liiks like this...

```ts
let framework = 'Next.js - SSR'

    const cfnAppHosting = new cdk.aws_amplify.CfnApp(this, 'mySubHosting', {
      name: `${props?.envVars.PRODUCTNAME}`,
      description: `myapp`,
      platform: amplifyAlpha.Platform.WEB_COMPUTE,
      repository: `https://github.com/${props?.envVars.OWNER}/${props?.envVars.REPO}`,
      accessToken: accessToken,
      enableBranchAutoDeletion: true,
      basicAuthConfig: { enableBasicAuth: false },
      autoBranchCreationConfig: {
        enableAutoBranchCreation: true,
        enableAutoBuild: true,
        framework,
        autoBranchCreationPatterns: ['development', 'feature/*'],
      },
      buildSpec: buildspec,
      environmentVariables: [
        { name: 'AMPLIFY_MONOREPO_APP_ROOT', value: 'frontend' },
        { name: '_CUSTOM_IMAGE', value: 'amplify:al2023' }
      ],
    })

```

Interestingly here is a screenshot from my amplify console - it shows that no Framework is specified - odd?
<img width="1166" alt="Screenshot 2024-05-26 at 10 13 07 pm" src="https://github.com/aws-amplify/amplify-backend/assets/39054710/000489e1-b717-4277-a797-aef0a570ab3c">
