### ISSUE TITLE
Cypress Log Downloads

### ISSUE THREAD

**Issue by BrookRichardson** [aws-amplify/amplify-backend#1756]
### Environment information

```plain text
NPM Packages:
  @aws-amplify/backend: 0.13.4
  @aws-amplify/backend-cli: 0.14.1
  aws-amplify: 6.4.0
  aws-cdk: 2.149.0
  aws-cdk-lib: 2.149.0
  typescript: 5.5.3
AWS environment variables:
  AWS_BRANCH = setx AWS_BRANCH feature-VITA-44-WithSecret-withAmplifyConfig
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
  AWS_STS_REGIONAL_ENDPOINTS = regional
No CDK environment variables
```

### Description

I have seen https://github.com/aws-amplify/amplify-backend/issues/1623#issuecomment-2168420004 that Cypress log downloading has been added to Amplify Gen 2. I have configured our project so that it uses cypress-mochawesome-reporter and this works well locally, but Amplify doesn't allow us to download the Cypress test result log. The logs aren't included in the download build artefacts or the download all logs options through the amplify sandbox UI.

Some have mentioned that aws `amplify get-job` works for them as a workaround, but the test artifacts return "The specified key does not exist." for me.

I have included our build script below. It includes a dynamic sandbox URL and `testartifacts` section.

Can anyone suggest what we need to do to get a copy of the sandbox Cypress output?

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
    test:
      commands:
        - 'npx cypress run --config baseUrl=https://$(echo ${AWS_BRANCH} | sed "s|/|-|g").${AWS_APP_ID}.amplifyapp.com --env userPassword=${CYPRESS_USER_PASSWORD} || exit 1'
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
    testArtifacts:
      baseDirectory: cypress/reports
      files:
        - '**/*'
  cache:
    paths:
      - .next/cache/**/*
      - .npm/**/*
      - .cache/Cypress
```

**Comment by Jay2113** [comment]
Hi @BrookRichardson 👋 , thanks for reaching out. Based on the provided build specification `amplify.yml` file, it appears that the test phase has been combined with the frontend phase, preventing you from downloading the test artifacts and Cypress reports. To resolve this issue, it's recommended to separate the test phase from the frontend phase. Here's the correct [syntax](https://docs.aws.amazon.com/amplify/latest/userguide/running-tests.html#add-tests-to-your-existing-amplify-app):

```
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - .next/cache/**/*
      - .npm/**/*
      - .cache/Cypress
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```

By separating the test phase from the frontend phase, you should be able to download the test artifacts and Cypress reports as expected. Please note that the test phase has its own artifacts section, which specifies the location and files to be included in the test artifacts.

**Comment by Jay2113** [comment]
@BrookRichardson Its likely the Amplify build specification file `amplify.yml` is misconfigured for the mochawesome report paths. You can refer to this sample [repository](https://github.com/Jay2113/amplify-cypress-demo) for implementing Cypress tests within your Amplify app. The repository includes an `amplify.yml` file at the root level, which overrides the build settings in the Amplify Console. You can fork the repository and deploy it to your AWS account. By default, the configured test and build will fail, but you can download the test artifacts and Cypress report from the failed build. Similarly, you can also download them for successful builds.

**Comment by BrookRichardson** [comment]
@Jay2113 I have taken a copy of that project and built it in one of our sandboxes and still do not get a download option of the mochawesome log. That menu item does not appear. In the event that a build works locally, but not in a sandbox we would like a way of reading the logs. Is this a known issue and what is the workaround?

**Comment by Jay2113** [comment]
@BrookRichardson After a build finishes (successfully or with failures), you can download the mochawesome log/reports by selecting the `View Cypress Results` option from the below menu. Are you unable to access this in the console?
![Screenshot 2024-08-06 at 11 21 09 AM](https://github.com/user-attachments/assets/409160b5-2af9-4e16-b3f1-b181bb77b75d)

**Comment by Abuitime** [comment]
@Jay2113 I added the test phase like in the sample [repository](https://github.com/Jay2113/amplify-cypress-demo), but I don't see any logs of the test phase running. I have a backend and frontend phase before the test phase. It seems like once the frontend phase is done, it just deploys. Any advice? 

```
version: 1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - .next/cache/**/*
      - node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - pm2 kill
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
```
