### ISSUE TITLE
AWS Amplify deployments failing for Next.js app (PNPM)

### ISSUE THREAD

**Issue by TomBell95** [aws-amplify/amplify-backend#1774]
### Description

None of our deployments are succeeding as each build reaching `Extracting cache...` and just hangs until it times out on 30 minutes.

Nothing has changed on our side for this to break and it seems a few issues have been raised around this already.

This is high priority as it is blocking our deployments!

- https://github.com/aws-amplify/amplify-backend/issues/1772
- https://github.com/aws-amplify/amplify-backend/issues/1765

As per @Jay2113's [comment here](https://github.com/aws-amplify/amplify-backend/issues/1765#issuecomment-2243243406), I have tried this and no success?

```yaml
            cache:
                paths:
                - node_modules/**/*
                - $(pnpm store path)
```
