### ISSUE TITLE
Web show blank white screen when deploy new code

### ISSUE THREAD

**Issue by sakshamjaiswal1** [aws-amplify/amplify-backend#1845]
### Environment information

```plain text
import react from "@vitejs/plugin-react";
import svgr from "vite-plugin-svgr";
import { join } from "path";
import { defineConfig, loadEnv } from "vite";
import { VitePWA } from "vite-plugin-pwa";
const manifestForPlugIn = {
  registerType: "autoUpdate",
  includeAssests: ["favicon.ico", "apple-touc-icon.png", "masked-icon.svg"],
  manifest: {
    name: "Chaquen",
    short_name: "Chaquen",
    description: "I am a simple vite app",
    icons: [
      {
        src: "/pwa/logo192.svg",
        sizes: "192x192",
        type: "image/png",
        purpose: "favicon",
      },
      {
        src: "/pwa/logo512.svg",
        sizes: "512x512",
        type: "/chaquen.svg",
        purpose: "favicon",
      },
      {
        src: "/pwa/logo512.svg",
        sizes: "180x180",
        type: "image/png",
        purpose: "apple touch icon",
      },
      {
        src: "/pwa/logo512.svg",
        sizes: "512x512",
        type: "image/png",
        purpose: "any maskable",
      },
    ],
    theme_color: "#171717",
    background_color: "#f0e7db",
    display: "standalone",
    scope: "/",
    start_url: "/",
    orientation: "portrait",
    devOptions: {
      enabled: true,
      type: "module",
    },
  },
};
```

### Description

![image](https://github.com/user-attachments/assets/2c70b017-020c-45f2-9d96-b4271c790dd5)

I am using Vite ts PWA app and hosted in amplify  and when i upload new code the screens go blank and i need to refresh atleast 3 times to get the page working.

Failed to load resource: the server responded with a status of 404 ()

**Comment by Jay2113** [comment]
Hi @sakshamjaiswal1 👋 , thanks for reaching out. I tried to reproduce the issue by accessing the [website](https://t20-staging.chaquen.io/) multiple times, but I was unable to replicate the outlined behavior. Are you encountering the 404 errors intermittently after a new deployment? 

Additionally, can you capture a HAR file and share it with us? This will be helpful for us to investigate the network requests and responses. Steps to capture the HAR file are outlined here: https://repost.aws/knowledge-center/support-case-browser-har-file.

**Comment by sakshamjaiswal1** [comment]
Hey this happens immediately i deploy the new code and after a hard refresh it goes away let me reproduce this and share the HAR file

**Comment by sakshamjaiswal1** [comment]
@Jay2113 hey did u find any solution for the above issue

**Comment by dk3775** [comment]
I am facing the same issue while deploying a nextjs project. Do we have any solutions?

**Comment by sakshamjaiswal1** [comment]
@dk3775 hey  can u share ur error also this is also @Jay2113 can u please have a look i have shared HAR file

**Comment by dk3775** [comment]
Technically there is nothing in console and the page is just blank. 
More info on my project -> Nextjs on using pnpm and custom build commands.

Here's my build.yml file

```
version: 1
frontend:
    phases:
        preBuild:
            commands:
                - 'npm install -g pnpm'
                - 'pnpm install'
                - 'npx prisma generate'
        build:
            commands:
                - 'pnpm iso:build'
    artifacts:
        baseDirectory: apps/isomorphic/.next
        files:
            - '**/*'
    cache:
        paths:
            - 'node_modules/**/*'
    start:
        commands:
             - 'pnpm run iso:start'
```

It takes approx 9-12 mins to complete the workflow.
