### ISSUE TITLE
I would like to see the ability to download test artifacts added to the Amplify console.

### ISSUE THREAD

**Issue by InsurTechLab-Amp** [aws-amplify/amplify-backend#2150]
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-hosting/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-hosting/issues?q=is%3Aissue+).
- [X] I have removed any sensitive information from my code snippets and submission.

### Amplify Hosting feature

Build settings, E2E Cypress tests

### Is your feature request related to a problem? Please describe:

When an E2E test FAILs and the deployment fails, the test artifact cannot be downloaded and the FAIL point cannot be verified.

### Describe how you'd like this feature to work

I would like to see the download button on the deploy screen of the Amplify console added to download test artifacts as well as build artifacts.

**Comment by InsurTechLab-Amp** [comment]
Thanks for your comment.
Amplify app id and branch name is below.

Amplify app id :  d1hrcn2hvtu4w3
branch name : PBI3236_for_issue

**Comment by Jay2113** [comment]
@InsurTechLab-Amp can you confirm if you are able to view the `Download artifacts` button within the `Test artifacts` tab in the console?
<img width="1918" alt="Screenshot 2024-10-30 at 12 29 11 PM" src="https://github.com/user-attachments/assets/4af734c6-9af8-413a-89a8-1b531d1749d4">

**Comment by InsurTechLab-Amp** [comment]
@Jay2113 
I don't see a tab for Test artifacts in the console.

![image](https://github.com/user-attachments/assets/5810a086-c0e9-4ae4-a850-368251cfd2c4)

The amplify.yml is written as follows.
```
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm audit --audit-level=high
        - npm run check
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files: 
      - '**/*'
  cache:
    paths:
      - .npm/**/*
      - node_modules/**/*

test:
  phases:
    preTest:
     commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install -g allure-commandline
        - npx playwright install
        - pm2 start npm -- start
        - wait-on http://localhost:5173
    test:
      commands:
        - npm run test -- --coverage
        - npm run test:e2e
        - npm run test:allure
        - npm run alluregenerate
    postTest:
      commands:
        - cp -r ./coverage ./dist/coverage
        - cp -r ./playwright-report ./dist/playwright-report 
        - cp -r ./playwright-screenshot ./dist/playwright-screenshot
        - cp -r ./playwright-video ./dist/playwright-video
        - cp -r ./allure-report ./dist/allure-report
        - pm2 kill 

  artifacts:
    baseDirectory: coverage
    files: 
      - '**/*'
```
The running log will be as follows.
![image](https://github.com/user-attachments/assets/a5de78d9-8b7f-408f-95db-7f14b1d97ded)

**Comment by matt-at-allera** [comment]
We're running into a similar situation where we cannot see the `Test Artifacts` tab nor do we see the option to `Download Test Artifacts` on individual builds:
<img width="217" alt="image" src="https://github.com/user-attachments/assets/8e2f0e90-ea25-4e13-9622-33c57b61625e">

This seems to have been broken since the migration to the new UI for the amplify front-end apps. The only way we can download test artifacts are by using the get-job command:
```
aws amplify get-job --region us-east-1 --app-id APP_ID --branch-name BRANCH_NAME --job-id JOB_NUMBER  --profile  AWS_PROFILE
```
(reference https://github.com/aws-amplify/amplify-backend/issues/1623)

**Comment by InsurTechLab-Amp** [comment]
Because the amplify.yml was created in the root of the project,
I pasted the contents of the amplify.yml into the console and the “test artifacts” tab appeared.
When I clicked on the “test artifacts” tab, the following error message appeared, but I was able to download the test artifacts by clicking the download button.
I do not know how to resolve the error because the preTest and test phases described in the error message are described in the YML. Could you please give me the amplify.yml when you took the screenshot of the “test artifacts” tab in the aforementioned answer?

![image](https://github.com/user-attachments/assets/1823f615-37c6-4020-b989-2005153144bf)

**amplify.yml**
```
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        - npm audit --audit-level=high
        - npm run check
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: dist
    files:
      - '**/*'
  cache:
    paths:
      - .npm/**/*
      - node_modules/**/*

test:
  phases:
    preTest:
     commands:
        - npm ci
        - npm install -g pm2
        - npm install -g wait-on
        - npm install -g allure-commandline
        - npx playwright install
        - pm2 start npm -- start
        - wait-on http://localhost:5173/
    test:
      commands:
        - npm run test -- --coverage
        - npm run test:e2e
        - npm run test:allure
        - npm run alluregenerate
    postTest:
      commands:
        # - cp -r ./coverage ./dist/coverage
        - cp -r ./playwright-report ./coverage/playwright-report
        - cp -r ./playwright-screenshot ./coverage/playwright-screenshot
        - cp -r ./playwright-video ./coverage/playwright-video
        - cp -r ./allure-report ./coverage/allure-report
        - pm2 kill

  artifacts:
    baseDirectory: coverage
    configFilePath: '**/index.html'
    files:
      - '**/*'
```
