### ISSUE TITLE
Amplify Deployment Failing in CodeCatalyst due to Bootstrap Error

### ISSUE THREAD

**Issue by ddotx** [aws-amplify/amplify-backend#2179]
### Environment information

```plain text
System:
OS: Linux 4.14 Amazon Linux 2023
CPU: (2) x64 Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Memory: 6.39 GB / 7.68 GB
Shell: /bin/bash
Binaries:
Node: 18.19.0 - /usr/local/bin/node
Yarn: undefined - undefined
npm: 10.2.3 - /usr/local/bin/npm
pnpm: undefined - undefined
NPM Packages:
@aws-amplify/auth-construct: 1.3.2
@aws-amplify/backend: 1.5.1
@aws-amplify/backend-auth: 1.2.0
@aws-amplify/backend-cli: 1.3.0
@aws-amplify/backend-data: 1.1.5
@aws-amplify/backend-deployer: 1.1.5
@aws-amplify/backend-function: 1.7.1
@aws-amplify/backend-output-schemas: 1.4.0
@aws-amplify/backend-output-storage: 1.1.2
@aws-amplify/backend-secret: 1.1.4
@aws-amplify/backend-storage: 1.2.1
@aws-amplify/cli-core: 1.1.3
@aws-amplify/client-config: 1.5.0
@aws-amplify/deployed-backend-client: 1.4.2
@aws-amplify/form-generator: 1.0.3
@aws-amplify/model-generator: 1.0.8
@aws-amplify/platform-core: 1.1.0
@aws-amplify/plugin-types: 1.3.0
@aws-amplify/sandbox: 1.2.3
@aws-amplify/schema-generator: 1.2.4
aws-amplify: 6.6.6
aws-cdk: 2.163.1
aws-cdk-lib: 2.163.1
typescript: 5.4.5
AWS environment variables:
AWS_CONTAINER_CREDENTIALS_FULL_URI = http://127.0.0.1:40133/codecatalyst/credentials/role/e7f9c211-5e3a-4163-91cf-474447206254
AWS_EXECUTION_ENV = AWS_ECS_EC2
AWS_BRANCH = main
AWS_APP_ID_STAGING = d3r7kyik0avkl4
AWS_REGION = us-west-2
AWS_APP_ID_PRODUCTION = d3druhmos9yuvs
AWS_CONTAINER_TOKEN_ENDPOINT = http://127.0.0.1:42727/caws/credentials/token/e337e182-3dfb-4adc-9b31-10d4d6a4e126
AWS_CA_BUNDLE = /codecatalyst/bootstrap/default-certs/cacert.pem
AWS_STS_REGIONAL_ENDPOINTS = regional
AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
No CDK environment variables
```

### Describe the bug

I'm encountering a "BootstrapNotDetectedError" when deploying my Amplify app in a CodeCatalyst workflow, even though the `cdk bootstrap` command runs successfully and reports "Environment aws://{YOUR_ACCOUNT_ID}/{YOUR_REGION} bootstrapped (no changes)."

```shell
BootstrapNotDetectedError: This AWS account and region has not been bootstrapped.
Resolution: Run `cdk bootstrap aws://{YOUR_ACCOUNT_ID}/{YOUR_REGION}` locally to resolve this.
Cause: Has the environment been bootstrapped
```

### Reproduction steps

Create a CodeCatalyst workflow from Amplify Gen 2 in the Cross-account deployments page
[cross-account-deployments](https://docs.amplify.aws/angular/deploy-and-host/fullstack-branching/cross-account-deployments/)

```yaml
    Configuration:
      Steps:
        - Run: npx aws-cdk@latest bootstrap aws://{YOUR_ACCOUNT_ID}/{YOUR_REGION}
        - Run: export CI=1
        - Run: npm ci
        - Run: npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
        - Run: if [ $AWS_BRANCH = "main" ]; then curl -X POST -d {}
            "`webhookUrl`&operation=startbuild" -H
            "Content-Type:application/json"; fi
```
