### ISSUE TITLE
BootstrapDetectionError: Unable to detect CDK bootstrap stack due to permission issues. On backend build Unable to deploy monorepo.

### ISSUE THREAD

**Issue by crafael23** [aws-amplify/amplify-backend#2222]
### Environment information

```plain text
System:
  OS: macOS 15.1
  CPU: (11) arm64 Apple M3 Pro
  Memory: 111.02 MB / 18.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 22.11.0 - ~/Library/pnpm/node
  Yarn: undefined - undefined
  npm: 10.9.0 - ~/Library/pnpm/npm
  pnpm: 9.12.3 - ~/Library/pnpm/pnpm
NPM Packages:
  @aws-amplify/auth-construct: Not Found
  @aws-amplify/backend: 1.7.0
  @aws-amplify/backend-auth: Not Found
  @aws-amplify/backend-cli: 1.4.2
  @aws-amplify/backend-data: Not Found
  @aws-amplify/backend-deployer: Not Found
  @aws-amplify/backend-function: Not Found
  @aws-amplify/backend-output-schemas: Not Found
  @aws-amplify/backend-output-storage: Not Found
  @aws-amplify/backend-secret: Not Found
  @aws-amplify/backend-storage: Not Found
  @aws-amplify/cli-core: Not Found
  @aws-amplify/client-config: Not Found
  @aws-amplify/deployed-backend-client: Not Found
  @aws-amplify/form-generator: Not Found
  @aws-amplify/model-generator: Not Found
  @aws-amplify/platform-core: Not Found
  @aws-amplify/plugin-types: Not Found
  @aws-amplify/sandbox: Not Found
  @aws-amplify/schema-generator: Not Found
  aws-amplify: 6.8.0
  aws-cdk: 2.166.0
  aws-cdk-lib: 2.166.0
  typescript: 5.5.4
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Describe the bug

I've been trying to setup a custom repository for a monorepo that will have several apps hosted on it.

The objective is to be able to share the backend with multple web and mobile apps.

I cant seem to  be able to build the backend.

I get the following error within the console when attempting to build it.

[BUILD.txt](https://github.com/user-attachments/files/17723633/BUILD.txt)

this is the current repo

https://github.com/KinuQ/kinuqmono

Im honestly not sure what is it that I'm doing wrong. 

I had another single repo app with a full fledged backend, and it is able to just go ahead and get deployed without an issue.

this is my amplify.yml for the CI process
```
version: 1
backend:
  phases:
    preBuild:
      commands:
        - corepack enable
        - pnpm install
    build:
      commands:
        - echo $AWS_BRANCH 
        - echo $AWS_APP_ID
        - pwd
        - cd packages/amplify
        - pwd
        - pnpm exec ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
        - cd ...
        
frontend:
  phases:
    build:
      commands:
        - pnpm turbo build
  artifacts:
    baseDirectory: apps/placeholderapp/dist
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
```

### Reproduction steps

fork my repo,

attempt to deploy on aws.

**Comment by ykethan** [comment]
Hey @crafael23, thank you for reaching out. From the build logs the message

```
credentials could not be used to assume 'arn:aws:iam::<account-id>:role/cdk-hnb659fds-deploy-role-<account-id>-us-east-2', but are for the right account. Proceeding anyway.
```
indicating the role may have been deleted or this may also occur if the account has [Service Control Policies](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html) that could be enforced on the IAM user/role on an account level within the organization.

Does local sandbox throw a similar error message?
On the IAM console, could you confirm if the role does exist? additionally, confirm if the account does not have any service control policies?

**Comment by crafael23** [comment]
@ykethan , for the moment local sandbox doesn't produce the same error

<img width="697" alt="image" src="https://github.com/user-attachments/assets/bcf468f9-2ade-4739-a176-316251dca241">

I do have other proyects hosted, a nextjs app and a little react SPA. Its only this one that gives the the problem, if I remove backend  deployment completely from te amplify.yml the problem goes away.

**Comment by crafael23** [comment]
@ykethan btw, because this is a test that I'm doing, I'm doing this on my personal root account. I've not touched Service control Policies.

**Comment by crafael23** [comment]
> Hey @crafael23, thank you for reaching out. From the build logs the message
> 
> ```
> credentials could not be used to assume 'arn:aws:iam::<account-id>:role/cdk-hnb659fds-deploy-role-<account-id>-us-east-2', but are for the right account. Proceeding anyway.�
> ```
> 
> indicating the role may have been deleted or this may also occur if the account has [Service Control Policies](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_scps.html) that could be enforced on the IAM user/role on an account level within the organization.
> 
> Does local sandbox throw a similar error message? On the IAM console, could you confirm if the role does exist? additionally, confirm if the account does not have any service control policies?

I just verified and the role does exist.
<img width="537" alt="image" src="https://github.com/user-attachments/assets/18094be1-b8a3-4966-ac79-b8c085acccb8">

**Comment by ykethan** [comment]
Hey @crafael23, thank you for the information. For a quick confirmation, does the app have a service role attached in the general settings? 

![image](https://github.com/user-attachments/assets/910204ce-7cff-4ff6-b8c9-c64ac4286887)

**Comment by crafael23** [comment]
@ykethan , the field for the service role is empty. Comparing it to the other react spa that i have there is no differnece, but comparing it to another nextjs app that i have deployed it appears to only have AmplifySSRLoggingRole and its not editable.

**Comment by crafael23** [comment]
I guess thats not what im supposed to do 
<img width="1193" alt="image" src="https://github.com/user-attachments/assets/b8872b41-a0dd-4951-bb0c-8ed0c4dc7e7f">

**Comment by crafael23** [comment]
@ykethan CDK deploy role doesnt have the amplify [AmplifyBackendDeployFullAccess](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/policies/details/arn%3Aaws%3Aiam%3A%3Aaws%3Apolicy%2Fservice-role%2FAmplifyBackendDeployFullAccess)

Ill try it out in a second.

**Comment by crafael23** [comment]
@ykethan 

I'm unsure weather this are the right settings for this
![image](https://github.com/user-attachments/assets/ddb5b8b4-d648-42fc-b4c2-25cf1656e7ea)

Since I see that in the  yaml you provided has the approot on ./apps.

**Comment by ykethan** [comment]
@crafael23 i was able to deploy this successfully using the following. could you try this and let us know if it deploys
![image](https://github.com/user-attachments/assets/0d823a96-251c-4ba5-a97e-fe48297dfbbb)


```
version: 1
applications:
  - appRoot: .
    backend:
      phases:
        preBuild:
          commands:
            - npm install -g pnpm
            - corepack enable
            - pnpm install
        build:
          commands:
            - echo $AWS_BRANCH
            - echo $AWS_APP_ID
            - cd packages/amplify
            - pnpm exec ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
            - cd ../..
    frontend:
      phases:
        build:
          commands:
            - pnpm turbo run build --filter="./apps/placeholderapp"
      artifacts:
        baseDirectory: apps/placeholderapp/dist
        files:
          - "**/*"
      cache:
        paths:
          - node_modules/**/*
          - .pnpm-store/**/*

```
