### ISSUE TITLE
Angular Project Init

### ISSUE THREAD

**Issue by akilisosa** [aws-amplify/amplify-backend#2225]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Angular

### Amplify APIs

Not applicable

### Amplify Version

v6

### Backend

None

### Environment information

<details>

```
# Put output below this line

I tried going through the quickstart guide twice. 

https://github.com/akilisosa/amplify-nom-kitties
https://github.com/akilisosa/amplify-nom-kitties-v2

I thought I followed the instructions to get it all working but it says build failure one the 2/3rd step deploying to amazon. When i run the project locally after npm install i get an error saying there isn't the amplify.outputs file or something to that effect. 

I am familiar with amplify v1 and haven't had issues there but now I am using this and it is extremely frustrating. 


```

</details>

### Describe the bug

I cannot get through the quickstart guide. 

### Expected behavior

I follow the quickstart guide and it runs in the browser. 

### Reproduction steps

follow the amplify angular quickstart guide, and let me know if its a problem with me or the guide. 

### Code Snippet

```javascript
// Put your code below this line.

```

### Log output

<details>

```
// Put your logs below this line

389

npm WARN EBADENGINE }

390

npm WARN EBADENGINE Unsupported engine {

391

npm WARN EBADENGINE package: '@angular-devkit/core@18.2.11',

392

npm WARN EBADENGINE required: {

393

npm WARN EBADENGINE npm: '^6.11.0 || ^7.5.6 || >=8.0.0',

394

npm WARN EBADENGINE node: '^18.19.1 || ^20.11.1 || >=22.0.0',

395

npm WARN EBADENGINE yarn: '>= 1.13.0'

396

npm WARN EBADENGINE },

397

npm WARN EBADENGINE current: { node: 'v18.18.2', npm: '9.8.1' }

398

npm WARN EBADENGINE }

399

npm WARN EBADENGINE Unsupported engine {

400

npm WARN EBADENGINE package: '@angular-devkit/schematics@18.2.11',

401

npm WARN EBADENGINE required: {

402

npm WARN EBADENGINE npm: '^6.11.0 || ^7.5.6 || >=8.0.0',

403

npm WARN EBADENGINE node: '^18.19.1 || ^20.11.1 || >=22.0.0',

404

npm WARN EBADENGINE yarn: '>= 1.13.0'

405

npm WARN EBADENGINE },

406

npm WARN EBADENGINE current: { node: 'v18.18.2', npm: '9.8.1' }

407

npm WARN EBADENGINE }

408

npm WARN EBADENGINE Unsupported engine {

409

npm WARN EBADENGINE package: '@schematics/angular@18.2.11',

410

npm WARN EBADENGINE required: {

411

npm WARN EBADENGINE npm: '^6.11.0 || ^7.5.6 || >=8.0.0',

412

npm WARN EBADENGINE node: '^18.19.1 || ^20.11.1 || >=22.0.0',

413

npm WARN EBADENGINE yarn: '>= 1.13.0'

414

npm WARN EBADENGINE },

415

npm WARN EBADENGINE current: { node: 'v18.18.2', npm: '9.8.1' }

416

npm WARN EBADENGINE }

417

2024-11-10T16:18:50.431Z [INFO]: added 266 packages in 10s

418

2024-11-10T16:18:50.432Z [INFO]: 49 packages are looking for funding

419

run `npm fund` for details

420

2024-11-10T16:18:50.448Z [INFO]: # Executing command: ng version

421

2024-11-10T16:18:50.479Z [WARNING]: Node.js version v18.18.2 detected.

422

The Angular CLI requires a minimum Node.js version of v18.19.

423

Please update your Node.js version or visit https://nodejs.org/ for additional instructions.

424

2024-11-10T16:18:50.483Z [ERROR]: !!! Build failed

425

2024-11-10T16:18:50.483Z [ERROR]: !!! Error: Command failed with exit code 3

426

2024-11-10T16:18:50.483Z [INFO]: # Starting environment caching...

427

2024-11-10T16:18:50.484Z [INFO]: # Environment caching completed

428


```

</details>

### Additional information and screenshots

I even redeployed it, it failed after 2 minutes and I am frustrated.

**Comment by akilisosa** [comment]
I have tried changing the build settings so many times and it still keeps coming in as node.18.18. 
according to amazon Q recomendations: 
```
version: 1
backend:
  phases:
    build:
      commands:
        - npm ci --cache .npm --prefer-offline
        - npx ampx pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - nvm install 20.11.1
        - nvm use 20.11.1
        - node -v
        - npm -v
        - npm cache clean --force
        - rm -rf node_modules
        - npm ci
    build:
      commands:
        - node -v
        - npm install -g @angular/cli@latest
        - ng version
        - ng build --configuration=production
  artifacts:
    baseDirectory: dist/amplify-angular-template/browser
    files:
      - '**/*'
  cache:
    paths:
      - .npm/**/*
      - node_modules/**/*
 ```


and a different one:
```
frontend:
  phases:
    preBuild:
      runtime: nodejs20.x
      commands:
        - npm ci
    build:
      runtime: nodejs20.x
      commands:
        - npm install -g @angular/cli
        - ng version
        - ng build --configuration=production
        ```
