### ISSUE TITLE
Cannot Create Gen2 Projects in my AWS Account at all --> Stack [CDKToolkit] already exists"

### ISSUE THREAD

**Issue by armenr** [aws-amplify/amplify-backend#777]
### Environment information

```plain text
Environment information is irrelevant - this is happening in the AWS Console
```

### Description

- Scaffold new generic Gen2 project
- Follow docs to add/install gen2
- Get back the right code (Auth and Data) in the repo
- Push repo to github
- Go to AWS Amplify Console
- Start Create new app workflow
- Connect to Git --> correctly detect repo --> correctly pick the right branch
- Steps fail...AWS Amplify Console is just stuck
- Open browser Console, discover the issue

Clicking the "Set Up" button for First time setup required causes the issue: 

![Screenshot 2023-12-06 at 12 49 56 AM](https://github.com/aws-amplify/amplify-backend/assets/7662191/56fc3d40-53e9-4350-9334-c828adbd6e60)

Here's what's in the Network tab of my browser console: 
```
<ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>AlreadyExistsException</Code>
    <Message>Stack [CDKToolkit] already exists</Message>
  </Error>
  <RequestId>6e2efefd-9751-4a38-81d1-898e3c44a140</RequestId>
</ErrorResponse>
```
![Screenshot 2023-12-06 at 12 52 21 AM](https://github.com/aws-amplify/amplify-backend/assets/7662191/74de324c-6919-4f1b-9bf1-63c3aa6f8ff5)

**Note:** This account was originally created and set up using the AWS Account Bootstrap Kit (which uses CDK). We haven't touched or updated that in a long, long while. I'm afraid I don't know what might break if we did, unless there are easy/not-risky steps for that.

**Comment by swaminator** [comment]
@armenr can you open cloudshell and try running `cdk bootstrap aws://ACCOUNT-NUMBER-1/REGION-1` ?

<img width="1161" alt="image" src="https://github.com/aws-amplify/amplify-backend/assets/2429410/9265d5d0-fddd-4787-8409-001758732f26">

**Comment by josefaidt** [comment]
Hey @armenr you can run this with pnpm! We're actively investigating a better mechanism to auto-detect your desired package manager, however in the meantime you'll need to modify the default build spec (`amplify.yml`) to use pnpm.

```yml
version: 1
backend:
  phases:
    build:
      commands:
        - echo WE MADE IT!
        - nvm use 18
        - corepack enable # set packageManager in package.json to automatically resolve pnpm version
        - pnpm install
        - pnpm amplify pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    build:
      commands:
        - pnpm run build
    postBuild:
	  commands:
		# prune node_modules and pnpm's store to only include prod dependencies
		- pnpm deploy --prod --ignore-scripts ./out
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: ./out/.amplify-hosting
    files:
      - "**/*"
  cache:
    paths:
      - $(pnpm store path)
```

For what it's worth this is derived from a Gen1 project's buildspec with a pnpm monorepo https://github.com/josefaidt/amplify-hosting-monorepo-with-pnpm/blob/main/amplify.yml

**Comment by josefaidt** [comment]
Hey @armenr this is the deploy command that wraps `cdk deploy` for persisted/branch environments, and is typically auto-configured in the default, generated buildspec (`amplify.yml`) file:

```yml
version: 1
backend:
  phases:
    build:
      commands:
        - nvm use 18
        - npm ci
        - npx amplify pipeline-deploy --branch $AWS_BRANCH --app-id $AWS_APP_ID
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

It will also set the necessary CDK context for deployments. Given its name it is not intended for manual deployments locally
